### ISSUE TITLE
Error when trying to download a collection

### ISSUE THREAD

**Issue by spakkko** [Kumar-Saksham/CSMM-CLI#3] opened 2020-05-14 23:15 UTC
The console return me this error whenever i try to download a steam collection of mod

Error while grabbing data: Evaluation failed: TypeError: Cannot read property 'innerText' of null
    at __puppeteer_evaluation_script__:9:7

![immagine](https://user-images.githubusercontent.com/65374084/81995010-78b30a80-9649-11ea-95b0-b7092905e54f.png)

**Comment by Kumar-Saksham** [comment] 2020-05-15 12:12
I cannot reproduce the error. Are you on the latest version of `csmm-cli` ? You can update using 
`npm i -g csmm-cli` command. 
Let me know if the problem persists.

**Comment by spakkko** [comment] 2020-05-16 01:46
I ran the update command but I get the same error when I try to download a collection

![immagine](https://user-images.githubusercontent.com/65374084/82107420-c4d47c80-9727-11ea-95d1-5afd9c446012.png)

**Comment by Kumar-Saksham** [comment] 2020-05-16 06:38
So, just to be sure. This doesn't happen when you install a single item/mod?

**Comment by spakkko** [comment] 2020-05-16 14:19
no problem with single mods so far

**Comment by Kumar-Saksham** [comment] 2020-05-17 07:49
Published a patch, which should fix this issue. 
Update `csmm-cli` (version will be >=0.5.1).
 
I am still not able to reproduce the error you are getting. I added few fallback method in case error occurs. Hopefully this fixes the issue.

View changes (Fix commit: 38743965ec971d33d013a97ef7bae74a4b955e44)

**Comment by guihleao** [comment] 2020-05-17 13:09
I'm also having the same problem =/

Executing prompt as administrator with csmm-cli 0.5.1

![image](https://user-images.githubusercontent.com/2766470/82147784-7e197c00-9826-11ea-860b-aa24f57942ed.png)

**Comment by Kumar-Saksham** [comment] 2020-05-17 18:01
Which version of node are you using?
you can check with `node -v` command

**Comment by guihleao** [comment] 2020-05-17 19:13
v12.16.3

**Comment by Kumar-Saksham** [comment] 2020-05-18 20:55
It seems like the problem was caused by incorrectly identifying collection id as an item id. Differentiation between item and collection was done on the basis of whether "collection" keyword appears on the steam page, which most probably will be different for different languages. Thanks @guihleao for the screenshot in Portuguese.
A new version 0.6.0 is published which should fix this issue.

**Comment by guihleao** [comment] 2020-05-18 21:35
@Kumar-Saksham thank you very much!

It's downloading now, but it keeps repeating forever, something about this:

![image](https://user-images.githubusercontent.com/2766470/82261272-1dc53000-9935-11ea-97d2-29ae8e025e15.png)
![image](https://user-images.githubusercontent.com/2766470/82261931-574a6b00-9936-11ea-9908-d069566c4ae2.png)

It looks like it can't register that the file was downloaded.

_Should I open another issue?_

**Comment by guihleao** [comment] 2020-05-18 21:46
> @Kumar-Saksham thank you very much!
> 
> It's downloading now, but it keeps repeating forever, something about this:
> 
> ![image](https://user-images.githubusercontent.com/2766470/82261931-574a6b00-9936-11ea-9908-d069566c4ae2.png)
> 
> It looks like it can't register that the file was downloaded.
> 
> _Should I open another issue?_

So what I've done to solve it:
Change system language to English temporarily and then back to my native language.

**Comment by Kumar-Saksham** [comment] 2020-05-18 21:47
can you send me screenshots of these 2 urls @guihleao 
https://steamcommunity.com/workshop/filedetails/?id=1625704117
https://steamcommunity.com/workshop/filedetails/?id=1625704117&l=english

**Comment by guihleao** [comment] 2020-05-18 21:50
Sure,

PT-BR:
![image](https://user-images.githubusercontent.com/2766470/82263010-66cab380-9938-11ea-9c13-68d1dd9304ad.png)

ENG:
![image](https://user-images.githubusercontent.com/2766470/82263041-73e7a280-9938-11ea-9ce5-f2b6e8b08730.png)

**Comment by Kumar-Saksham** [comment] 2020-05-18 22:04
I have forced english language while fetching the data, so it should fix the last issue @guihleao mentioned. 
Update to 0.6.1

**Comment by guihleao** [comment] 2020-05-18 22:08
yeeee perfect! thank you very much again!

**Comment by Kumar-Saksham** [comment] 2020-05-19 07:07
I am closing the issue now. @spakkko, let me know if the fix didn't work for you.

**Closed by Kumar-Saksham** 2020-05-19 07:07 UTC
